export const RECEIVE_TODOS = 'todo/RECEIVE'
export const FIND_TODOS = 'todo/FIND'
export const ADD_TODO = 'todo/ADD'
export const TOGGLE_TODO = 'todo/TOGGLE'
export const CLEAR_TODOS = 'todo/CLEAR'
export const EDIT_TODO = 'todo/EDIT'
export const DELETE_TODO = 'todo/DELETE'
